const heroSlides = [
    {
        title: "Defile Her Veiled Virtue",
        description: "Slip into our Arabic hijabi skinsuits and ravage the taboo, draping yourself in submissive, exotic flesh that begs to be violated.",
        features: [
            "Exotic desert whore aesthetic for depraved fantasies",
            "Tight fit to flaunt submissive, breedable curves",
            "Dominate her culture with every sinful step"
        ],
        buttonText: "Ravage Her Forbidden Body",
        image: "img/hijabi.png",
        alt: "Hijabi Skinsuit",
        background: "url('img/hero-section-background.png')"
    },
    {
        title: "Enslave the Perfect Housewife",
        description: "Become the ultimate subservient slut with our housewife skinsuits, built to serve, please, and be used in every filthy way imaginable.",
        features: [
            "Prime white breeder body for total submission",
            "Curves crafted for rough, degrading use",
            "Live the fantasy of a broken domestic bitch"
        ],
        buttonText: "Own Her Pathetic Soul",
        image: "img/housewife.png",
        alt: "Housewife Skinsuit",
        background: "url('img/hero-section-background.png')"
    },
    {
        title: "Defile Her Pregnant Womb",
        description: "Our Black pregnant skinsuits let you defile sacred motherhood, with lush, fertile curves that scream for perverse exploitation.",
        features: [
            "Voluptuous Black breeder body for taboo thrills",
            "Swollen curves to degrade and dominate",
            "Perfect for sick, primal fetishes"
        ],
        buttonText: "Violate Her Fertile Flesh",
        image: "img/pregnant.png",
        alt: "Pregnant Skinsuit",
        background: "url('img/hero-section-background.png')"
    }
];

const products = [
    {
        name: "Alina",
        age: 32,
        ethnicity: "Russian",
        background: "Twitch Streamer",
        height: { feet: "5'6\"", meters: "1.68 m" },
        weight: { pounds: "130 lbs", kilograms: "59 kg" },
        measurements: { inches: "34B-26-36", cm: "86-66-91" },
        pussyType: "Shaved, Tight",
        sexualPreference: "Bisexual",
        kinks: ["Public Humiliation", "Roleplay", "Voyeurism"],
        personality: ["Charismatic", "Submissive", "Playful"],
        appearance: ["Fair skin", "Brown hair", "Normal body build"],
        previousOwners: 2,
        price: "$15,999",
        image: "img/russian_wives/1.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Alina teased legions of desperate viewers on Twitch, her brown hair bouncing as she flaunted her tight 34B-26-36 curves in skimpy outfits, her shaved pussy begging for tips and attention. Her skin lets you hijack her streamer slut persona, perfect for degrading her in front of a virtual audience, forcing her into vile, voyeuristic acts for their sick pleasure."
    },
    {
        name: "Vika",
        age: 35,
        ethnicity: "Russian",
        background: "Social Media Influencer",
        height: { feet: "5'8\"", meters: "1.73 m" },
        weight: { pounds: "125 lbs", kilograms: "57 kg" },
        measurements: { inches: "36C-24-35", cm: "91-61-89" },
        pussyType: "Waxed, Plump",
        sexualPreference: "Heterosexual",
        kinks: ["Exhibitionism", "Bondage", "Anal Play"],
        personality: ["Seductive", "Confident", "Kinky"],
        appearance: ["Tanned skin", "Black hair", "Fit"],
        previousOwners: 1,
        price: "$13,599",
        image: "img/russian_wives/2.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Vika built an empire on Instagram, her tanned, fit 36C-24-35 body and waxed, plump pussy posing in barely-there lingerie for perverted followers. Her skin traps you in her influencer whore flesh, ideal for exploiting her fame in degrading, public displays of kinky submission to satisfy the darkest urges."
    },
    {
        name: "Alexandra",
        age: 21,
        ethnicity: "Russian",
        background: "University Student",
        height: { feet: "5'4\"", meters: "1.63 m" },
        weight: { pounds: "110 lbs", kilograms: "50 kg" },
        measurements: { inches: "32A-22-34", cm: "81-56-86" },
        pussyType: "Trimmed, Petite",
        sexualPreference: "Curious",
        kinks: ["Teacher Fantasies", "Gangbang", "Corruption"],
        personality: ["Innocent", "Submissive", "Corruptible"],
        appearance: ["Fair skin", "Blonde hair", "Green eyes", "Skinny"],
        previousOwners: 0,
        price: "$2,799",
        image: "img/russian_wives/3.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Alexandra was the naive university girl, her green eyes and blonde hair hiding filthy fantasies behind her petite 32A-22-34 frame and trimmed pussy, studying late while dreaming of violation. Her skin lets you corrupt her innocent facade, turning her into a depraved coed for taboo classroom gangbangs or perverse professor fantasies."
    },
    {
        name: "Mila",
        age: 18,
        ethnicity: "Russian",
        background: "Oligarch’s Daughter",
        height: { feet: "5'2\"", meters: "1.57 m" },
        weight: { pounds: "105 lbs", kilograms: "48 kg" },
        measurements: { inches: "32B-23-33", cm: "81-58-84" },
        pussyType: "Shaved, Delicate",
        sexualPreference: "Bisexual",
        kinks: ["Pet Play", "Spanking", "Elite Orgies"],
        personality: ["Spoiled", "Submissive", "Exotic"],
        appearance: ["Fair skin", "Dark hair", "Petite"],
        previousOwners: 0,
        price: "$100,000",
        image: "img/russian_wives/4.png",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Mila lounged in luxury as an oligarch’s daughter, her pouty lips and petite 32B-23-33 body with a delicate shaved pussy spoiled by wealth, secretly craving rough handling at elite orgies. Her skin lets you defile her pampered flesh, transforming her into a submissive toy for sadistic, high-society debauchery and forbidden exploitation."
    },
    {
        name: "Yulia",
        age: 20,
        ethnicity: "Russian",
        background: "Cosplayer",
        height: { feet: "5'3\"", meters: "1.60 m" },
        weight: { pounds: "115 lbs", kilograms: "52 kg" },
        measurements: { inches: "34B-25-35", cm: "86-64-89" },
        pussyType: "Waxed, Tight",
        sexualPreference: "Pansexual",
        kinks: ["Cosplay Fetish", "Group Play", "Humiliation"],
        personality: ["Playful", "Submissive", "Creative"],
        appearance: ["Fair skin", "Blue and black hair", "Petite"],
        previousOwners: 0,
        price: "$8,699",
        image: "img/russian_wives/5.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Yulia pranced at cons in skimpy cosplay, her blue and black hair and petite 34B-25-35 frame with a waxed, tight pussy drawing lecherous stares from creepy fans she teased. Her skin lets you become her playful, costumed slut, perfect for degrading in perverse anime-themed gangbangs or taboo convention hookups."
    },
    {
        name: "Tanya",
        age: 27,
        ethnicity: "Russian",
        background: "Sales Employee at Blackwood Inc.",
        height: { feet: "5'5\"", meters: "1.65 m" },
        weight: { pounds: "120 lbs", kilograms: "54 kg" },
        measurements: { inches: "34A-24-34", cm: "86-61-86" },
        pussyType: "Shaved, Plump",
        sexualPreference: "Heterosexual",
        kinks: ["Office Domination", "Degradation", "Foot Worship"],
        personality: ["Ambitious", "Submissive", "Charming"],
        appearance: ["Fair skin", "Red hair", "Skinny"],
        previousOwners: 2,
        price: "$11,499",
        image: "img/russian_wives/6.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Tanya flirted her way through sales at Blackwood Inc., her red hair and skinny 34A-24-34 body with a plump shaved pussy bending over desks to close deals, hiding a submissive core. Her skin lets you exploit her corporate bitch persona, turning her into a degraded office slave for sadistic boardroom violations."
    },
    {
        name: "Anna",
        age: 25,
        ethnicity: "Russian",
        background: "Escort",
        height: { feet: "5'7\"", meters: "1.70 m" },
        weight: { pounds: "135 lbs", kilograms: "61 kg" },
        measurements: { inches: "36D-26-38", cm: "91-66-97" },
        pussyType: "Trimmed, Juicy",
        sexualPreference: "Bisexual",
        kinks: ["Rough Sex", "Cum Play", "Degradation"],
        personality: ["Seductive", "Voluptuous", "Degradable"],
        appearance: ["Tanned skin", "Dark hair", "Curvy"],
        previousOwners: 7,
        price: "$1,799",
        image: "img/russian_wives/7.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Anna sold her curvy, tanned 36D-26-38 body with a juicy trimmed pussy as a Moscow escort, her dark hair and pouty lips servicing rich clients in seedy hotel rooms, thriving on degradation. Her skin lets you inhabit her whorish flesh, perfect for turning her into a cum-drenched toy for the vilest, taboo paid encounters."
    },
    {
        name: "Eugenia",
        age: 22,
        ethnicity: "Russian",
        background: "Unemployed Girlfriend",
        height: { feet: "5'3\"", meters: "1.60 m" },
        weight: { pounds: "112 lbs", kilograms: "51 kg" },
        measurements: { inches: "32B-24-34", cm: "81-61-86" },
        pussyType: "Shaved, Delicate",
        sexualPreference: "Heterosexual",
        kinks: ["Pet Play", "Domestic Servitude", "Light Bondage"],
        personality: ["Loyal", "Submissive", "Cute"],
        appearance: ["Fair skin", "Blonde hair with pink tips", "Petite"],
        previousOwners: 0,
        price: "$5,599",
        image: "img/russian_wives/8.webp",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Eugenia was the clingy girlfriend, her blonde hair with pink tips and petite 32B-24-34 body with a delicate shaved pussy always eager to please her man, hiding filthy desires behind her cute smile. Her skin lets you defile her loyal devotion, transforming her into a submissive pet for perverse, domestic degradation fantasies."
    },
    {
        name: "Ekaterina",
        age: 40,
        ethnicity: "Russian",
        background: "Politician",
        height: { feet: "5'9\"", meters: "1.75 m" },
        weight: { pounds: "140 lbs", kilograms: "64 kg" },
        measurements: { inches: "34C-26-36", cm: "86-66-91" },
        pussyType: "Waxed, Tight",
        sexualPreference: "Bisexual",
        kinks: ["Power Play", "Humiliation", "Group Domination"],
        personality: ["Dominant", "Powerful", "Seductive"],
        appearance: ["Fair skin", "Blonde hair", "Slender"],
        previousOwners: 3,
        price: "$65,899",
        image: "img/russian_wives/9.png",
        flag: "https://flagcdn.com/w40/ru.png",
        description: "Ekaterina commanded boardrooms and backroom deals as a ruthless politician, her pretty 34C-26-36 frame with a waxed, tight pussy masking a cruel streak while seducing allies and enemies alike. Her skin lets you seize her dominant persona, perfect for breaking her powerful facade in degrading, taboo political scandals and sadistic power-play orgies."
    }
];

const collectionName = "Russian Wives";
const collectionDescription = "Dive into a depraved collection of Russian women, crafted for men craving to exploit sultry Russian beauties in every perverse fantasy.";